version: '3.8'

services:
  web:
    image: php:8.0-apache
    container_name: mondelib-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mondelib_net
    working_dir: /var/www/html
    environment:
      - PHP_EXTENSIONS=mbstring,gd,zip,pdo,pdo_mysql
    command: bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libzip-dev zip unzip && docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install gd zip pdo_mysql && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mondelib-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mondelib_db
      MYSQL_USER: se_user
      MYSQL_PASSWORD: se_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mondelib_net
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mondelib-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - mondelib_net

networks:
  mondelib_net:

volumes:
  db_data:
