<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Album',
  2 => 'Announcement',
  3 => 'Authorization',
  4 => 'Comment',
  5 => 'Core',
  6 => 'Event',
  7 => 'Fields',
  8 => 'Harmony',
  9 => 'Invite',
  10 => 'Messages',
  11 => 'Network',
  12 => 'Payment',
  13 => 'Storage',
  14 => 'User',
  15 => 'Video',
); ?>