<h2>Language Translator Plugin</h2>

<?php if (engine_count($this->navigation)): ?>
    <div class='tabs seaocore_admin_tabs'>
        <?php echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
    </div>
<?php endif; ?>
<div> This page list down all the language packs generated by translating file from one language to another. You can download, edit or delete these language pack. You can also create a new language pack by clicking on ‘New Language Pack’. </div>
<div>
<br/>
<br />
  <a href="<?php echo $this->url(array('action' => 'index')) ?>" class="buttonlink sitetranslator_icon_add" title="<?php echo $this->translate('New Language Pack'); ?>">New Language Pack</a>
</div>
<br />
<div class="sitetranslator_admin_order_list">
  <div class="list_head">
    <div style="width:25%">
      Language
    </div>
      
    <div style="width:35%;text-align: center;">
     Number Of Characters
    </div>
      <div style="width:40%;" class='admin_table_bold'>
          Options
      </div>
  </div>

    <div id='order-element'>      
      <ul>
        <?php foreach ($this->listLanguages as $language => $size ) : ?>
                <?php if($size == 0 ): continue; endif; ?>
          <li>
            <div style="width:25%;" class='admin_table_bold'>
              <?php echo $this->languages[$language]?>
            </div>
            <div style="width:35%;text-align: center;" class='admin_table_bold'>
              <?php echo $size ?>
            </div>
            <div style="width:40%;" class='admin_table_bold'>
                <a href="<?php echo $this->url(array('module'=>'core','controller'=>'language','action' => 'export', 'locale' => $language),'admin_default') ?>">download</a>
                |<a href="<?php echo $this->url(array('module'=>'sitetranslator','controller'=>'translator','action' => 'phrases', 'source_language' => 'en','target_language' => $language,'csv_files' => 'all'),'admin_default') ?>"> missing phrases </a> 
                |<a href="<?php echo $this->url(array('module'=>'core','controller'=>'language','action' => 'edit', 'locale' => $language),'admin_default') ?>"> edit</a> 
                
          <?php if( $this->defaultLanguage != $language ): ?>
            | <?php echo $this->htmlLink(array('module'=>'core','controller'=>'language','action'=>'delete',  'locale'=>$language), 'delete', array('class'=>'smoothbox')) ?>
          <?php else: ?>
            | default
          <?php endif; ?>
          
            </div>
          </li>
<?php endforeach; ?>
      </ul>
    </div>
 </div>